#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu May 10 12:40:10 2018

@author: wun35247
"""

import pygame

pygame.init()

# Nastavení okna
wd_widht = 640
wd_height = 480
window = pygame.display.set_mode((wd_widht,wd_height))
pygame.display.set_caption("Ultimate super mega Lodě")

clock = pygame.time.Clock()  #casovac okna - pro jednotlivé instance nastavíme později

#Definování barev pro snadnější použití pozdeji
black = (0,0,0)
white = (255,255,255)
brigth_red = (255,0,0)
red  =(200,0,0)
bright_green = (0,255,0)
bright_blue = (0,0,255)
blue = (0,0,200)
button_gray = (199,199,199)
button_mouse_gray = (153,153,153)
bg_blue = (98,218,255)

#Definování fontů pro texty
small_button_text = pygame.font.SysFont("comicsansms",20)    #(font,size)
largetext = pygame.font.Font("freesansbold.ttf" ,100)


def text_object(text,font,color):       #dk how it works but it does xD
    textSurface = font.render(text, True, color)
    return textSurface, textSurface.get_rect()

def render_text(text,font,x,y,color = black):
    TextSurf, TextRect = text_object(text,font,color)
    TextRect.center = (x,y)
    window.blit(TextSurf, TextRect)
    pygame.display.update()
    
    
def button(label,color,mouse_on_color,x,y,w,h,action=None): #all numbers must be int
    x -= w//2           #center the coorinates
    y -= h//2
    hitbox = range(x,x+w) #hitbox of the button 
    hitboy = range(y,y+h)
    
    mouse = pygame.mouse.get_pos()  #coordinates of mouse pointer
    click = pygame.mouse.get_pressed()
    
    if mouse[0] in hitbox and mouse[1] in hitboy: #change color no mouse hover
        pygame.draw.rect(window,mouse_on_color,(x,y,w,h))
        
        if click[0] and action != None: #execute click action if any
            action()
    else:
        pygame.draw.rect(window,color,(x,y,w,h))
        
    render_text(label,small_button_text,(x+w//2),(y+h//2)) #add text to button
    
def quit_game():
    pygame.quit()
    quit()    

def shit_placing():
    shit = True    
        
    x = 50        
    y = 50
    
    while shit: #very important to have a cycle!!!
    
        for event in pygame.event.get(): #so it can be closed
            if event == pygame.QUIT:
                quit_game()
                        
        window.fill(bg_blue)
        
        button(" ",red,brigth_red,5,5,10,10,quit_game)
        
        for x in range(0,10):
            x = x*15 + 50
            for y in range(0,10):
                y = y*15 + 50
                button(" ",blue,bright_blue,x,y,10,10) 
        
        
        pygame.display.update()   #redner things to screen
        
        clock.tick(60) #15 FPS

    
    
def test_screen():
    test = True
    while test: #very important to have a cycle!!!
    
        for event in pygame.event.get(): #so it can be closed
            if event == pygame.QUIT:
                quit_game()
                
                
        window.fill(bg_blue)
        render_text("Shits",largetext,wd_widht//2,wd_height//3) #text text
        
        button("Play",button_gray,button_mouse_gray,wd_widht//2,(wd_height//3)+50,150,25,shit_placing) #test buton
        button("Quit",button_gray,button_mouse_gray,wd_widht//2,(wd_height//3)+100,150,25,quit_game)
        
        pygame.display.update()   #redner things to screen
        
        clock.tick(15) #15 FPS
             
test_screen()
pygame.quit()
quit() 